GET http://localhost:5211/games

###
GET http://localhost:5211/games/4

###
POST http://localhost:5211/games
Content-Type: application/json

{
    "name": "Street Ball Fighters Street",
    "price" : 99.99,
    "genreId" : 2,
    "releaseDate" : "2011-11-08"
}


###
PUT http://localhost:5211/games/1
Content-Type: application/json

{
    "name": "Street Ball Fighters Street Ball FightersStreet Ball FightersStreet Ball FightersStreet Ball FightersStreet Ball FightersStreet Ball Fighters",
    "genre": "RolePlaying",
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

###
DELETE http://localhost:5211/games/1